# Secrets
RIOT_API_KEY = "<RIOT-API-KEY>"
FCM_API_KEY = "<FCM-API-KEY>"

# Targets
TARGET_PLAYERS = []

# Detect config
DETECT_PERIOD_SEC = 60
TIMES_OF_DETECT_PERIOD_ON_PLAYING = 6

# Logging
USE_DEBUG_LOG = False